//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RacePuntos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalle_puntos
    {
        public Nullable<int> id_estacion { get; set; }
        public Nullable<int> id_puntos_servicio { get; set; }
        public Nullable<int> id_puntos_actuales { get; set; }
        public Nullable<int> puntos_compra { get; set; }
        public int id_detalle_puntos { get; set; }
    
        public virtual estaciones_de_servicio estaciones_de_servicio { get; set; }
        public virtual puntos puntos { get; set; }
    }
}
