//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RacePuntos.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class vehiculo
    {
        public string documento_usuario { get; set; }
        public string placa_vehiculo_cliente { get; set; }
        public string codigo_vehiculo { get; set; }
        public string marca_vehiculo { get; set; }
        public string referencia_vehiculo { get; set; }
        public string cilindraje_vehiculo { get; set; }
        public int id_vehiculo { get; set; }
    
        public virtual detalle_vehiculos detalle_vehiculos { get; set; }
        public virtual personas personas { get; set; }
    }
}
